name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: muhbayu/nodejs-deploy

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$GITHUB_RUN_NUMBER

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running Container
      run: |
        docker kill service-1 || true
        docker run -d -p 3000:3000 --name service-1 $IMAGE_NAME:$GITHUB_RUN_NUMBER
  
  clean:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cleaning Images
      run: docker image prune -f || true
